{
 "title": "hw dashboard",
 "time": { "from": "2023-08-15T07:26:59.685Z", "to": "2023-08-15T21:28:06.975Z" },
 "panels": [
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{job=\"nodeexporter\", instance=\"nodeexporter:9100\"}",
     "legendFormat": "MemTotal"
    },
    {
     "expr": "node_memory_MemFree_bytes{job=\"nodeexporter\", instance=\"nodeexporter:9100\"}",
     "legendFormat": "MemFree"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{job=\"nodeexporter\",mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "CPU Utilization"
    }
   ]
  },
  {
   "title": "Filesystem capacity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{mountpoint=\"/\"}",
     "legendFormat": "Total avaliable space"
    },
    {
     "expr": "node_filesystem_size_bytes{mountpoint=\"/\"}",
     "legendFormat": "Total used space"
    }
   ]
  },
  {
   "title": "Load Average ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{job=\"nodeexporter\"}",
     "legendFormat": "CPU_LA1"
    },
    {
     "expr": "node_load5{job=\"nodeexporter\"}",
     "legendFormat": "CPU_LA5"
    },
    {
     "expr": "node_load15{job=\"nodeexporter\"}",
     "legendFormat": "CPU_LA15"
    }
   ]
  }
 ]
}