---
all:
  hosts:
    sonar-01:
      ansible_host: ip
    nexus-01:
      ansible_host: ip
  children:
    sonarqube:
      hosts:
        sonar-01:
    nexus:
      hosts:
        nexus-01:
    postgres:
      hosts:
        sonar-01:
  vars:
    ansible_connection_type: paramiko
    ansible_user: centos
    ansible_ssh_private_key_file: "~/.ssh/..."