stages:
  - build

image: docker:20.10.5
variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ''
  DOCKER_DRIVER: overlay2
  
services:
  - name: docker:20.10.5-dind
    alias: docker


builder:
    stage: build
    script:
        - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
        - docker build -t $CI_REGISTRY_IMAGE:gitlab-$CI_COMMIT_SHORT_SHA .
        - docker push $CI_REGISTRY_IMAGE:gitlab-$CI_COMMIT_SHORT_SHA


