FROM nginx

MAINTAINER Kunaev Nikita <azero.kunaev@gmail.com>

ENV TZ=Eurome/Moscow

RUN echo -e "<html>\n\
<head>\n\
Hey, Netology\n\
</head>\n\
<body>\n\
<h1>I'm DevOps Engineer! </h1>\n</body>\n\
</html>" > /usr/share/nginx/html/index.html

