---
all:
  hosts:
    nexus-01:
      ansible_host: 51.250.86.214
  children:
    nexus:
      hosts:
        nexus-01:
  vars:
    ansible_connection_type: paramiko
    ansible_user: kuanev
    ansible_ssh_private_key_file: '~/.ssh/settings'