---
all:
  hosts:
    jenkins-master-01:
      ansible_host: 158.160.108.204
    jenkins-agent-01:
      ansible_host: 158.160.98.57
  children:
    jenkins:
      children:
        jenkins_masters:
          hosts:
            jenkins-master-01:
        jenkins_agents:
          hosts:
              jenkins-agent-01:
  vars:
    ansible_connection_type: paramiko
    ansible_user: cloud-user
    ansible_ssh_private_key_file: '~/.ssh/settings'